;;; pandoc-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pandoc-mode.el

(autoload 'pandoc-mode "pandoc-mode" "\
Minor mode for interacting with Pandoc.

This is a minor mode.  If called interactively, toggle the
`Pandoc mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `pandoc-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

\\{pandoc-mode-map}

(fn &optional ARG)" t)
(autoload 'conditionally-turn-on-pandoc "pandoc-mode" "\
Turn on pandoc-mode if a pandoc settings file exists.
This is for use in major mode hooks.")
(register-definition-prefixes "pandoc-mode" '("pandoc-"))


;;; Generated autoloads from pandoc-mode-utils.el

(register-definition-prefixes "pandoc-mode-utils" '("abbreviations" "ascii" "atx-headers" "base-header-level" "bibl" "chapters" "cit" "columns" "def" "dpi" "email-obfuscation" "eol" "epub-" "filter" "gladtex" "highlight-style" "html-q-tags" "id-prefix" "ipynb-output" "jsmath" "katex" "latex" "listings" "lua-filter" "metadata" "mimetex" "natbib" "number-" "old-dashes" "pdf-engine" "preserve-tabs" "reference-" "request-header" "resource-path" "shift-heading-level-by" "slide-level" "smart" "syntax-definition" "tab" "template" "title-prefix" "track-changes" "variable" "verbose" "webtex" "wrap"))

;;; End of scraped data

(provide 'pandoc-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pandoc-mode-autoloads.el ends here
