#!/bin/bash
# open the URL "about:config" in Firefox. In there I right clicked and
# created a new string called "network.protocol-handler.app.mailto" with a
# value of the path to where you put this script

MAILTO_URL="$@"

#Strip off the protocol
MAIL_DATA=$(echo "$MAILTO_URL" | /bin/sed -s 's/^mailto://I')

#Get Recipient and strip it off
RECIPIENT=$(echo "$MAIL_DATA" | cut -d? -f1 -)
MAIL_DATA=$(echo "$MAIL_DATA" | /bin/sed -s "s/^$RECIPIENT//")

#Get Subject,BCC, and CC
SUBJECT=$(echo "$MAIL_DATA" | \
/bin/sed -s 's/.*?subject=//I' | /bin/sed -s 's/?.*//')
BCC=$(echo "$MAIL_DATA" | /bin/sed -s 's/.*?bcc=//I' | \
/bin/sed -s 's/?.*//')
CC=$(echo "$MAIL_DATA" | /bin/sed -s 's/.*?cc=//I' | \
/bin/sed -s 's/?.*//')

#Call mutt in an aterm
gnome-terminal -x muttng "$RECIPIENT" -b "$BCC" -c "$CC" -s "$SUBJECT"

# Last Modified: Wed 13 Jul 2005 05:11:42 PM PDT
