-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["subs"] = {
            [1] = {
                ["type"] = "WIonWS",
                ["name"] = "WIonWS<1>",
                ["switchto"] = true,
                ["sizepolicy"] = 1,
                ["split_tree"] = {
                    ["tls"] = 786,
                    ["tl"] = {
                        ["regparams"] = {
                            ["flags"] = 128,
                            ["type"] = "WFrame",
                            ["name"] = "WFrame<1>",
                            ["subs"] = {
                            },
                            ["frame_style"] = "frame-tiled-ionws",
                        },
                        ["type"] = "WSplitRegion",
                    },
                    ["dir"] = "vertical",
                    ["brs"] = 14,
                    ["br"] = {
                        ["type"] = "WSplitST",
                    },
                    ["type"] = "WSplitSplit",
                },
            },
            [2] = {
                ["type"] = "WFrame",
                ["frame_style"] = "frame-scratchpad",
                ["sizepolicy"] = 5,
                ["hidden"] = true,
                ["flags"] = 132,
                ["passive"] = false,
                ["name"] = "*scratchpad*",
                ["subs"] = {
                    [1] = {
                        ["type"] = "WClientWin",
                        ["windowid"] = 10485764,
                        ["switchto"] = true,
                        ["sizepolicy"] = 2,
                        ["checkcode"] = 1,
                    },
                },
                ["geom"] = {
                    ["y"] = 160,
                    ["x"] = 695,
                    ["w"] = 531,
                    ["h"] = 480,
                },
                ["layer"] = 2,
            },
        },
        ["type"] = "WScreen",
        ["name"] = "WScreen",
    },
}

