;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((nil . ((tab-width . 8)
         (sentence-end-double-space . t)
         (fill-column . 72)
         (emacs-lisp-docstring-fill-column . 72)
         (bug-reference-url-format . "https://debbugs.gnu.org/%s")
         (diff-add-log-use-relative-names . t)
         (vc-prepare-patches-separately . nil)))
 (log-edit-mode . ((log-edit-font-lock-gnu-style . t)
                   (log-edit-setup-add-author . t)
                   (vc-git-log-edit-summary-target-len . 50)
                   (fill-column . 64)))
 (change-log-mode . ((mode . bug-reference)
                     (add-log-time-zone-rule . t)
                     (fill-column . 74)))
 (emacs-lisp-mode . ((mode . bug-reference-prog)
                     (electric-quote-comment . nil)
                     (electric-quote-string . nil)
                     (indent-tabs-mode . nil)))
 (Texinfo-mode . ((mode . bug-reference-prog)
                  (electric-quote-comment . nil)
                  (electric-quote-string . nil)
                  (fill-column . 74))))
