;;; geiser-guile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from geiser-guile.el

(autoload 'connect-to-guile "geiser-guile" "\
Start a Guile REPL connected to a remote process.

Start the external Guile process with the flag --listen to make
it spawn a server thread." t)
(geiser-activate-implementation 'guile)
(autoload 'run-guile "geiser-guile" "\
Start a Geiser Guile REPL." t)
(autoload 'switch-to-guile "geiser-guile" "\
Start a Geiser Guile REPL, or switch to a running one." t)
(register-definition-prefixes "geiser-guile" '("geiser-guile-" "guile"))

;;; End of scraped data

(provide 'geiser-guile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geiser-guile-autoloads.el ends here
