;;; geiser-chicken-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from geiser-chicken.el

(geiser-activate-implementation 'chicken)
(geiser-implementation-extension 'chicken "release-info")
(geiser-implementation-extension 'chicken "meta")
(geiser-implementation-extension 'chicken "setup")
(autoload 'run-chicken "geiser-chicken" "\
Start a Geiser Chicken REPL." t)
(autoload 'switch-to-chicken "geiser-chicken" "\
Start a Geiser Chicken REPL, or switch to a running one." t)
(autoload 'connect-to-chicken "geiser-chicken" "\
Connect to a remote Geiser Chicken REPL." t)
(register-definition-prefixes "geiser-chicken" '("chicken" "connect-to-chicken" "geiser-chicken"))

;;; End of scraped data

(provide 'geiser-chicken-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geiser-chicken-autoloads.el ends here
