;;; mingus-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mingus.el

(autoload 'mingus-help "mingus" "\
Help screen for `mingus'." t)
(autoload 'mingus "mingus" "\
MPD Interface by Niels Giesen, Useful and Simple.

Actually it is just named after that great bass player.

(fn &optional SET-VARIABLES)" t)
(autoload 'mingus-browse "mingus" "\
Switch to buffer *Mingus Browser* and start the Mingus browsing experience." t)
(register-definition-prefixes "mingus" '("*mingus-" "_mingus-" "mingus-"))


;;; Generated autoloads from mingus-stays-home.el

(autoload 'mingus-burns "mingus-stays-home" nil t)
(register-definition-prefixes "mingus-stays-home" '("*mingus-b-session*" "mingus-"))

;;; End of scraped data

(provide 'mingus-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mingus-autoloads.el ends here
