;;; geiser-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from geiser.el

(defconst geiser-elisp-dir (file-name-directory load-file-name) "\
Directory containing Geiser's Elisp files.")
(autoload 'geiser-version "geiser-version" "\
Echo Geiser's version." t)
(autoload 'geiser-unload "geiser-reload" "\
Unload all Geiser code." t)
(autoload 'geiser-reload "geiser-reload" "\
Reload Geiser code." t)
(autoload 'geiser "geiser-repl" "\
Start a Geiser REPL." t)
(autoload 'run-geiser "geiser-repl" "\
Start a Geiser REPL." t)
(autoload 'geiser-connect "geiser-repl" "\
Start a Geiser REPL connected to a remote server." t)
(autoload 'geiser-connect-local "geiser-repl" "\
Start a Geiser REPL connected to a remote server over a Unix-domain socket." t)
(autoload 'geiser-repl-switch "geiser-repl" "\
Switch to a running one Geiser REPL." t)
(autoload 'geiser-mode "geiser-mode" "\
Minor mode adding Geiser REPL interaction to Scheme buffers." t)
(autoload 'turn-on-geiser-mode "geiser-mode" "\
Enable Geiser's mode (useful in Scheme buffers)." t)
(autoload 'turn-off-geiser-mode "geiser-mode" "\
Disable Geiser's mode (useful in Scheme buffers)." t)
(mapc (lambda (group) (custom-add-load group (symbol-name group)) (custom-add-load 'geiser (symbol-name group))) '(geiser geiser-repl geiser-autodoc geiser-doc geiser-debug geiser-faces geiser-mode geiser-image geiser-implementation geiser-xref))
(autoload 'geiser-mode--maybe-activate "geiser-mode")
(add-hook 'scheme-mode-hook #'geiser-mode--maybe-activate)


;;; Generated autoloads from geiser-autodoc.el

(register-definition-prefixes "geiser-autodoc" '("geiser-autodoc-"))


;;; Generated autoloads from geiser-base.el

(register-definition-prefixes "geiser-base" '("geiser--"))


;;; Generated autoloads from geiser-capf.el

(register-definition-prefixes "geiser-capf" '("geiser-capf-"))


;;; Generated autoloads from geiser-compile.el

(register-definition-prefixes "geiser-compile" '("geiser-"))


;;; Generated autoloads from geiser-completion.el

(register-definition-prefixes "geiser-completion" '("geiser-"))


;;; Generated autoloads from geiser-connection.el

(register-definition-prefixes "geiser-connection" '("geiser-con"))


;;; Generated autoloads from geiser-custom.el

(register-definition-prefixes "geiser-custom" '("geiser-custom-"))


;;; Generated autoloads from geiser-debug.el

(register-definition-prefixes "geiser-debug" '("geiser-debug-"))


;;; Generated autoloads from geiser-doc.el

(register-definition-prefixes "geiser-doc" '("geiser-doc-"))


;;; Generated autoloads from geiser-edit.el

(register-definition-prefixes "geiser-edit" '("geiser-"))


;;; Generated autoloads from geiser-eval.el

(register-definition-prefixes "geiser-eval" '("geiser-eval-"))


;;; Generated autoloads from geiser-image.el

(register-definition-prefixes "geiser-image" '("geiser-"))


;;; Generated autoloads from geiser-impl.el

 (defvar geiser-active-implementations nil)
 (defvar geiser-implementations-alist nil)
(defun geiser-activate-implementation (impl) (add-to-list 'geiser-active-implementations impl))
(defun geiser-impl--add-to-alist (kind what impl &optional append) (add-to-list 'geiser-implementations-alist (list (list kind what) impl) append))
(defun geiser-implementation-extension (impl ext) "\
Add to `geiser-implementations-alist' an entry for extension EXT." (geiser-impl--add-to-alist 'regexp (format "\\.%s\\'" ext) impl t))
(register-definition-prefixes "geiser-impl" '("define-geiser-implementation" "geiser-" "with--geiser-implementation"))


;;; Generated autoloads from geiser-log.el

(register-definition-prefixes "geiser-log" '("geiser-"))


;;; Generated autoloads from geiser-menu.el

(register-definition-prefixes "geiser-menu" '("geiser-menu--"))


;;; Generated autoloads from geiser-mode.el

(register-definition-prefixes "geiser-mode" '("geiser-" "turn-o"))


;;; Generated autoloads from geiser-popup.el

(register-definition-prefixes "geiser-popup" '("geiser-popup-"))


;;; Generated autoloads from geiser-reload.el

(register-definition-prefixes "geiser-reload" '("geiser-"))


;;; Generated autoloads from geiser-repl.el

(register-definition-prefixes "geiser-repl" '("geiser"))


;;; Generated autoloads from geiser-syntax.el

(register-definition-prefixes "geiser-syntax" '("geiser-syntax--"))


;;; Generated autoloads from geiser-table.el

(register-definition-prefixes "geiser-table" '("geiser-table-"))


;;; Generated autoloads from geiser-xref.el

(register-definition-prefixes "geiser-xref" '("geiser-xref-"))

;;; End of scraped data

(provide 'geiser-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geiser-autoloads.el ends here
