;;; parseclj-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from parseclj.el

(register-definition-prefixes "parseclj" '("parseclj-"))


;;; Generated autoloads from parseclj-alist.el

(register-definition-prefixes "parseclj-alist" '("parseclj-"))


;;; Generated autoloads from parseclj-ast.el

(register-definition-prefixes "parseclj-ast" '("parseclj-ast-"))


;;; Generated autoloads from parseclj-lex.el

(register-definition-prefixes "parseclj-lex" '("parseclj-lex-"))


;;; Generated autoloads from parseclj-parser.el

(register-definition-prefixes "parseclj-parser" '("parseclj-"))

;;; End of scraped data

(provide 'parseclj-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; parseclj-autoloads.el ends here
