;;; geiser-racket-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from geiser-racket.el

(autoload 'geiser-racket-connect "geiser-racket" "\
Start a Racket REPL connected to a remote process.

The remote process needs to be running a REPL server started
using start-geiser, a procedure in the geiser/server module." t)
(geiser-activate-implementation 'racket)
(geiser-implementation-extension 'racket "rkt[dl]?")
(add-to-list 'auto-mode-alist '("\\.rkt\\'" . scheme-mode))
(autoload 'run-racket "geiser-racket" "\
Start a Geiser Racket REPL." t)
(register-definition-prefixes "geiser-racket" '("geiser-racket-" "racket"))

;;; End of scraped data

(provide 'geiser-racket-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geiser-racket-autoloads.el ends here
