;;; chronos-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from chronos.el

(autoload 'chronos-add-timer "chronos" "\
Add a timer to expire at time TIME with message MESSAGE.

TIME can be absolute or relative (positive countdown or negative
countup) to now or (with the PREFIX argument) the selected
timer.

(fn TIME MESSAGE PREFIX)" t)
(autoload 'chronos-select-timer "chronos" "\
Select a timer from `chronos-standard-timers'." t)
(autoload 'chronos-add-timers-from-string "chronos" "\
Add a timer (or timers) based on TIMERS-STRING.

TIMER-STRING consists of timer specifications separated by `+'s.

Timer specifications consist of an expiry specification and a
message separated by a `/'.

If the PREFIX argument is selected, the (first) timer will be
relative to the selected timer, otherwise current time.

Subsequent timers in the string will be relative to the previous timer.

A list of timers ((exp msg) ...) is returned.

(fn TIMERS-STRING PREFIX)" t)
(autoload 'chronos-reset-timer "chronos" "\
Reset selected timer." t)
(register-definition-prefixes "chronos" '("chronos-"))

;;; End of scraped data

(provide 'chronos-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; chronos-autoloads.el ends here
