;;; d-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from d-mode.el

(add-to-list 'auto-mode-alist '("\\.d[i]?\\'" . d-mode))
(defvar d-mode-hook nil "\
*Hook called by `d-mode'.")
(custom-autoload 'd-mode-hook "d-mode" t)
(autoload 'd-mode "d-mode" "\
Major mode for editing code written in the D Programming Language.

See http://dlang.org for more information about the D language.

The hook `c-mode-common-hook' is run with no args at mode
initialization, then `d-mode-hook'.

Key bindings:
\\{d-mode-map}

(fn)" t)
(register-definition-prefixes "d-mode" '("d-"))

;;; End of scraped data

(provide 'd-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; d-mode-autoloads.el ends here
