#!/bin/zsh
#
# change default behaviors for the basics

. ~/.zsh/vars

# Host specific aliases
case $HOSTNAME in
	stryder)
		alias outside="weatherget -s USVA0068 -m"
	;;
	naia)
		alias outside="weatherget -s USVA0068 -m"
	;;
	theg4)
		alias outside="weatherget -s USOH0269 -S"
	;;
	*)
		alias outside="weatherget -s USVA0068 -m"
	;;
esac

alias mv="mv -v"
alias mmv="noglob zmv -W"
alias rm="rm -v"
alias cp="cp -v"
#alias firefox="aoss firefox"
alias mplayer="mplayer -idx"
alias wget="wget --timeout 10"
alias grep="grep --color=auto"
alias sm="python ~/code/statmac/statmac.py"
#alias irb="irb --simple-prompt"

#function call
alias ex=extract_archive

# abreviations

# todos!
alias t="$HOME/todo/todo.py"
alias tl="t ls"
alias ta="t add"

# basics
alias c="clear"
alias l="cd ."
alias ll='ls -ahl $CM_CONF_LS_DIRGROUP $CM_CONF_LS_COLOR | more $CM_CONF_MORE_COLOR; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
alias e="emacsclient -na \"\""
alias v="vim"
alias wh="when ci --past=0 --future=3"
alias cdc="cd; clear"
alias cdp="cd /u/jmickey/p4"
alias ciq="centericq"

# more interesting aliases :D
alias nowifi="sudo ifconfig eth0 down; sudo route add default gw 192.168.1.1"
alias themini="ssh 192.168.1.2"
alias nsl='netstat -alnp --protocol=inet | grep -v CLOSE_WAIT'
alias cslab="rdesktop -u codemac -p - -K -a 16 -g 1150x767  rlogin.cs.vt.edu"
alias cdwav="cdrecord -v -eject -pad speed=48 dev=/dev/cdrom -dao -audio -swab"
alias rchem="rdesktop -u jbm -p - -K -a 16 -g 1280x667 chemad1"
alias boggle='echo "No no no, Mr. Brian Braun-Duin"'
alias p4-describe-all='p4 changes -s pending -u jmickey | awk "{print $2}" | xargs p4 describe -s | grep pending'
# borrowed from comcleod
#alias fucking-sad-face="p4 changes -s pending -u jmickey |awk '{print \$2}' | xargs p4 describe -s | grep pending | sed -e s/comcleod@// | awk '{system( \"echo P4PORT=perforce.ironport.com:1666 > P4ENV && echo P4CLIENT=\" $4 \" >> P4ENV && p4 change -d \" $2 \" && p4 client -d \" $4 ) }'

# auto open images
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}="feh -FZd"

# auto open movies
alias -s {mpg,mpeg,avi,ogm,wmv,m4v,mp4,mov}="mplayer -idx"

# auto open audio
alias -s {mp3,ogg,wav,flac}="cplay"

# auto open web addresses
alias -s {html,php,com,net,org,gov}="firefox"

# auto open regular files
alias -s txt="vim"
alias -s pdf="xpdf"

## global pipe aliases
alias -g M="| most" #	<< most is the best pager evar.
alias -g G="| grep"
alias -g E="| egrep"
alias -g S="| sed -r -e"
alias -g XC="| xclip" 
alias -g X="| xmessage -file -" 
alias -g XO="| xmessage -button okay:0,cancel:1 -default okay -file -" 
alias -g ZO="| zenity --text-info"
