#!/bin/zsh
#
export PYTHONBIN=""

if [[ -f /opt/local/bin/python ]]; then
    export PYTHONBIN=$(/opt/local/bin/python -V 2>&1 | sed "s#^Python \(.*\)\$#/usr/local/Cellar/python/\1/bin#g")
#    # virtualenv
#    export WORKON_HOME=$HOME/.virtualenvs
#    export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
#    . $PYTHONBIN/virtualenvwrapper.sh
#    alias ve='workon'
#    alias ve.deactivate='deactivate'
#    alias ve.mk='mkvirtualenv --no-site-packages'
#    alias ve.mk_withsitepackages='mkvirtualenv'
#    alias ve.rm='rmvirtualenv'
#    alias ve.switch='workon'
#    alias ve.add2virtualenv='add2virtualenv'
#    alias ve.cdsitepackages='cdsitepackages'
#    alias ve.cd='cdvirtualenv'
#    alias ve.lssitepackages='lssitepackages'
fi

export GOROOT=/usr/lib/go
export GOPATH="$HOME/code/go"
export PATH="/opt/local/bin:/opt/local/sbin:/opt/java/bin:/opt/kde/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/sbin:/usr/sbin:$PYTHONBIN:$HOME/bin:$HOME/.cabal/bin:$HOME/work/tools_ig/fritz:$HOME/code/go/bin:/opt/google-appengine-go:$PATH"
export MOZILLA_FIVE_HOME=/opt/mozilla/bin/mozilla
case ${OSTYPE} in
    darwin*)
	#export TERM=xterm
	export EDITOR=emacsclient
	export GIT_EDITOR=emacsclient
	;;
    linux*)
	export EDITOR=emacsclient
	export GIT_EDITOR=emacsclient
	;;
    *)
	export EDITOR=emacsclient
	export GIT_EDITOR=emacsclient
	;;
esac
export GPG_TTY=`tty`
#export MANPAGER="col -b | vim -c 'set ft=man nonu nomod nolist' -"
export MANPAGER=most
export MAIL=$HOME/mail/default
export PACKAGER="Jeff Mickey <j@codemac.net>"
export CHROOT_SHELL="$HOME/archlinux/chroot"
export GEM_HOME=$HOME/.gem
export GEM_PATH=$HOME/.gem:/usr/lib/ruby/gems/1.9.1
export BROWSER=firefox
export CVS_RSH="ssh"


# Fix this fucking bullshit. raster should work but depends on xshm which they can't seem to program right to save their fucking lives.
export QT_GRAPHICSSYSTEM=native

# watch for people
watch=(notme)                   # watch for everybody but me
export LOGCHECK=300                    # check every 5 min for login/logout activity

# The format of login / logout reports if the watch parameter is set.
# Default is `%n has %a %l from %m'.
# Recognizes the following escape sequences:
#   %n = name of the user that logged in/out.
#   %a = observed action, i.e. "logged on" or "logged off".
#   %l = line (tty) the user is logged in on.
#   %M = full hostname of the remote host.
#   %m = hostname up to the first `.'.
#   %t or %@ = time, in 12-hour, am/pm format.
#   %w = date in `day-dd' format.
#   %W = date in `mm/dd/yy' format.
#   %D = date in `yy-mm-dd' format.
# WATCHFMT='%n %a %l from %m at %t.'
# WATCHFMT='*knock* *knock* Follow the white rabbit => %n %a %l from %m at %t.'
# WATCHFTM=print '\e[1;35m%B[%b\e[1;32m%B%n%b\e[1;35m%B]%b \e[1;34m%U%a%u \e[1;35mfrom terminal \e[1;31m%M \e[1;35mat \e[1;33m%U%T%u\e[0m''
#WATCHFMT="[%B%t%b] %B%n%b has %a %B%l%b from %B%M%b"
export WATCHFMT="%B->%b %n has just %a %(l:tty%l:%U-Ghost-%u)%(m: from %m:)"
export REPORTTIME=10
export _JAVA_OPTIONS=-Dawt.useSystemAAFontSettings=on
