#!/bin/zsh
#
export PATH=$PATH:/opt/java/bin:/opt/kde/bin:/sbin:/usr/sbin:$HOME/bin:$HOME/hacks:$HOME/code/depot_tools:.
export MOZILLA_FIVE_HOME=/opt/mozilla/bin/mozilla
export EDITOR=vim
#export MANPAGER="col -b | vim -c 'set ft=man nonu nomod nolist' -"
export MANPAGER=most
export MAIL=/home/jeff/mail/default
export PACKAGER="Jeff Mickey <jmickey@netapp.com>"
export CHROOT_SHELL="/home/jeff/archlinux/chroot"
export CVS_RSH="ssh"

# watch for people
watch=(notme)                   # watch for everybody but me
export LOGCHECK=300                    # check every 5 min for login/logout activity

# The format of login / logout reports if the watch parameter is set.
# Default is `%n has %a %l from %m'.
# Recognizes the following escape sequences:
#   %n = name of the user that logged in/out.
#   %a = observed action, i.e. "logged on" or "logged off".
#   %l = line (tty) the user is logged in on.
#   %M = full hostname of the remote host.
#   %m = hostname up to the first `.'.
#   %t or %@ = time, in 12-hour, am/pm format.
#   %w = date in `day-dd' format.
#   %W = date in `mm/dd/yy' format.
#   %D = date in `yy-mm-dd' format.
# WATCHFMT='%n %a %l from %m at %t.'
# WATCHFMT='*knock* *knock* Follow the white rabbit => %n %a %l from %m at %t.'
# WATCHFTM=print '\e[1;35m%B[%b\e[1;32m%B%n%b\e[1;35m%B]%b \e[1;34m%U%a%u \e[1;35mfrom terminal \e[1;31m%M \e[1;35mat \e[1;33m%U%T%u\e[0m''
#WATCHFMT="[%B%t%b] %B%n%b has %a %B%l%b from %B%M%b"
export WATCHFMT="%B->%b %n has just %a %(l:tty%l:%U-Ghost-%u)%(m: from %m:)"
export REPORTTIME=10
