#!/bin/zsh
#
# list contents of directory on every "cd"
function chpwd
{
	integer ls_lines="$(ls -C | wc -l)"
	if [[ $ls_lines -eq 0 ]]; then
		echo No files found: Empty Directory 
	else
		ls -hl --group-directories-first $CM_CONF_LS_COLOR | more $CM_CONF_MORE_COLOR
		echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -l | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -l | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"
	fi
# source and create project environment
	if [[ -f $PWD/.projectenv ]]; then
		. $PWD/.projectenv
	fi
}

# reload zshrc
function src()
{
        autoload -U zrecompile
                [[ -f ~/.zshrc ]] && zrecompile -p ~/.zshrc
				for i in "$(find ~/.zsh/ -type f)"; do
					[[ -f $i ]] && zrecompile -p $i
					[[ -f $i.zwc.old ]] && rm -f $i.zwc.old
				done
                [[ -f ~/.zcompdump ]] && zrecompile -p ~/.zcompdump
                [[ -f ~/.zcompdump ]] && zrecompile -p ~/.zcompdump
                [[ -f ~/.zshrc.zwc.old ]] && rm -f ~/.zshrc.zwc.old
                [[ -f ~/.zcompdump.zwc.old ]] && rm -f ~/.zcompdump.zwc.old
                source ~/.zshrc
}

function pic2gif {
    
}

# hg rcs functions
function hgs() { hg status $* }
function hgl() { hg log $* }
function hgc() { hg commit -m "$*" }
function hgp() { hg push $* }
function hga() { hg add $* }

# burn m3u
function burnm3u()
{
   dos2unix "$1"
   sed '/^#/d' "$1" | tr '\n' '\0' | xargs -0 k3b --datacd 
}

# To be used like foldl latex *.tex
function mapL {
    emulate -L zsh
    for i in ${~argv[2,-1]} ; do
        eval "${argv[1]} ${i}"
    done
}
alias map="noglob mapL"



# To be used like foldr /etc/init.d/{foo,bar,baz} restart
function mapR {
    emulate -L zsh
    for i in ${~argv[1,-2]} ; do
        $i ${argv[-1]}
    done
}
alias mapr="noglob mapR"

# Found in the mailinglistarchive from Zsh (IIRC ~1996)
# MISC: Search in the $HISTFILE and select result to execute
function selhist()
{
	emulate -L zsh
	local TAB=$'\t';
	(( $# < 1 )) && {
		echo "Usage: $0 command"
		return 1
	};
	cmd=(${(f)"$(grep -w $1 $HISTFILE | sort | uniq | pr -tn)"})
	print -l $cmd | less -F
	echo -n "enter number of desired command [1 - $(( ${#cmd[@]} - 1 ))]: "
	local answer
	read answer
	print -z "${cmd[$answer]#*$TAB}"
}

# query extended file attributes
fattr() {
	local val=$(getfattr -n user.$1 --only-values $REPLY 2>/dev/null) 
	[[ -n $val && (( -z $2 || $val = $~2 )) ]]
}

# SEARCH: summarized google, ggogle, mggogle, agoogle and fm
function search()
{
	case "$1" in
		-g) ${BROWSER:-lynx} http://www.google.com/search\?q=$2
		;;
		-u) ${BROWSER:-lynx} http://groups.google.com/groups\?q=$2
		;;
		-m) ${BROWSER:-lynx} http://groups.google.com/groups\?selm=$2
		;;
		-a) ${BROWSER:-lynx} http://groups.google.com/groups\?as_uauthors=$2
		;;
		-c) ${BROWSER:-lynx} http://search.cpan.org/search\?query=$2\&mode=module
		;;
		-f) ${BROWSER:-lynx} http://freshmeat.net/search/\?q=$2\&section=projects
		;;
		-F) ${BROWSER:-lynx} http://www.filewatcher.com/\?q=$2
		;;
		-G) ${BROWSER:-lynx} http://www.rommel.stw.uni-erlangen.de/~fejf/cgi-bin/pfs-web.pl\?filter-search_file=$2
		;;
		-s) ${BROWSER:-lynx} http://sourceforge.net/search/\?type=soft\&q=$2
		;;
		-w) ${BROWSER:-lynx} http://de.wikipedia.org/wiki/$2
		;;
		-W) ${BROWSER:-lynx} http://en.wikipedia.org/wiki/$2
		;;
		-d) lynx -source "http://dict.leo.org?$2" | grep -i "TABLE.*/TABLE" | sed "s/^.*\(<TABLE.*TABLE>\).*$/<HTML><BODY>\1<\/BODY><\/HTML>/" | lynx -stdin -dump -width=$COLUMNS -nolist;
		;;
		*) 
		  echo "Usage: $0 {-g | -u | -m | -a | -f | -c | -F | -s | -w | -W | -d}"
		  echo "	-g:  Searching for keyword in google.com"
		  echo "	-u:  Searching for keyword in groups.google.com"
		  echo "	-m:  Searching for message-id in groups.google.com"
		  echo "	-a:  Searching for Authors in groups.google.com"
		  echo "	-c:  Searching for Modules on cpan.org."
		  echo "	-f:  Searching for projects on Freshmeat."
		  echo "	-F:  Searching for packages on FileWatcher."
		  echo "	-G:  Gentoo file search."
		  echo "	-s:  Searching for software on Sourceforge."
		  echo "	-w:  Searching for keyword at wikipedia (german)."
		  echo "	-W:  Searching for keyword at wikipedia (english)."
		  echo "	-d:  Query dict.leo.org ;)"
	esac
}

extract_archive () {
    local old_dirs current_dirs lower
    lower=${(L)1}
    old_dirs=( *(N/) )
    if [[ $lower == *.tar.gz || $lower == *.tgz ]]; then
        tar xvzf $1
    elif [[ $lower == *.gz ]]; then
        gunzip $1
    elif [[ $lower == *.tar.bz2 || $lower == *.tbz ]]; then
        tar xvjf $1
    elif [[ $lower == *.tar.xz || $lower == *.txz ]]; then
	tar xvJf $1
    elif [[ $lower == *.bz2 ]]; then
        bunzip2 $1
    elif [[ $lower == *.zip ]]; then
        unzip $1
    elif [[ $lower == *.rar ]]; then
        unrar e $1
    elif [[ $lower == *.tar ]]; then
        tar xvf $1
    elif [[ $lower == *.lha ]]; then
        lha e $1
    else
        print "Unknown archive type: $1"
        return 1
    fi
    # Change in to the newly created directory, and
    # list the directory contents, if there is one.
    current_dirs=( *(N/) )
    for i in {1..${#current_dirs}}; do
        if [[ $current_dirs[$i] != $old_dirs[$i] ]]; then
            cd $current_dirs[$i]
            break
        fi
    done
}

#compdef '_files -g "*.gz *.tgz *.bz2 *.tbz *.zip *.rar *.tar *.lha"' extract_archive
