-- This file has been generated by Ion. Do not edit.
return {
    ["date"] = {
        ["date_format"] = "%a %Y.%m.%d %H:%M",
    },
    ["load"] = {
        ["important_threshold"] = 1.5,
        ["critical_threshold"] = 4,
        ["update_interval"] = 10000,
    },
    ["mail"] = {
    },
}

