-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1280,
                    ["h"] = 800,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1280,
                            ["h"] = 800,
                        },
                        ["split_tree"] = {
                            ["tls"] = 787,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 13,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WFrame",
                ["sizepolicy"] = "free_glue",
                ["managed"] = {
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchpad*",
                ["pseudomodal"] = true,
                ["hidden"] = true,
                ["mode"] = 1,
                ["geom"] = {
                    ["y"] = 160,
                    ["x"] = 320,
                    ["w"] = 640,
                    ["h"] = 480,
                },
                ["level"] = 1024,
            },
        },
    },
}

