-- This file has been generated by notion. Do not edit.
return {
    ["mail"] = {
    },
    ["battery"] = {
        ["status_display"] = {
            ["charging"] = "â\134\145",
            ["discharging"] = "â\134\147",
            ["full"] = " ",
        },
        ["blink_on_discharge"] = true,
        ["content_format"] = "|| %s",
        ["bat_no"] = 0,
        ["info_format"] = "%s%.f%s",
        ["info_data"] = {
            [1] = "status",
            [2] = "percentage",
            [3] = "status",
        },
    },
    ["date"] = {
        ["formats"] = {
            ["utctime"] = "!%H:%M",
        },
        ["date_format"] = "%a %Y-%m-%d %H:%M",
    },
    ["load"] = {
    },
}

