-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1.0,
                                    ["name"] = "Tiling Frame",
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["brs"] = 960.0,
                            ["tls"] = 960.0,
                            ["tl"] = {
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["brs"] = 15.0,
                                ["tls"] = 1065.0,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["saved_x"] = 0.0,
                                        ["saved_w"] = 1920.0,
                                        ["managed"] = {
                                        },
                                        ["mode"] = 1.0,
                                        ["saved_y"] = 0.0,
                                        ["name"] = "WFrame<1>",
                                        ["saved_h"] = 1065.0,
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "horizontal",
                            ["type"] = "WSplitSplit",
                        },
                        ["sizepolicy"] = "full",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1080.0,
                        },
                        ["name"] = "WTiling",
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1080.0,
                },
                ["name"] = "WGroupWS",
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 1.0,
                                ["name"] = "WFrame<3>",
                                ["managed"] = {
                                },
                                ["type"] = "WFrame",
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["sizepolicy"] = "full",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1080.0,
                        },
                        ["name"] = "WTiling<2>",
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1080.0,
                },
                ["name"] = "WGroupWS<2>",
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["type"] = "WGroupWS",
            },
            [3] = {
                ["level"] = 0.0,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["split_tree"] = {
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["brs"] = 16.0,
                            ["tls"] = 1064.0,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1.0,
                                    ["name"] = "WFrame<5>",
                                    ["managed"] = {
                                        [1] = {
                                            ["level"] = 0.0,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1.0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 1.0,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 31457404.0,
                                                    ["geom"] = {
                                                        ["y"] = 0.0,
                                                        ["x"] = 0.0,
                                                        ["w"] = 1918.0,
                                                        ["h"] = 1043.0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["name"] = "WGroupCW",
                                            ["geom"] = {
                                                ["y"] = 20.0,
                                                ["x"] = 1.0,
                                                ["w"] = 1918.0,
                                                ["h"] = 1043.0,
                                            },
                                            ["type"] = "WGroupCW",
                                        },
                                        [2] = {
                                            ["level"] = 0.0,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1.0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 2.0,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 35651604.0,
                                                    ["geom"] = {
                                                        ["y"] = 8.0,
                                                        ["x"] = 1.0,
                                                        ["w"] = 1917.0,
                                                        ["h"] = 1026.0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["name"] = "WGroupCW<1>",
                                            ["geom"] = {
                                                ["y"] = 20.0,
                                                ["x"] = 1.0,
                                                ["w"] = 1918.0,
                                                ["h"] = 1043.0,
                                            },
                                            ["type"] = "WGroupCW",
                                        },
                                        [3] = {
                                            ["level"] = 0.0,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1.0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 3.0,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 37748749.0,
                                                    ["geom"] = {
                                                        ["y"] = 6.0,
                                                        ["x"] = 3.0,
                                                        ["w"] = 1912.0,
                                                        ["h"] = 1030.0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["name"] = "WGroupCW<2>",
                                            ["geom"] = {
                                                ["y"] = 20.0,
                                                ["x"] = 1.0,
                                                ["w"] = 1918.0,
                                                ["h"] = 1043.0,
                                            },
                                            ["type"] = "WGroupCW",
                                        },
                                        [4] = {
                                            ["level"] = 0.0,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1.0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 4.0,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 39845901.0,
                                                    ["geom"] = {
                                                        ["y"] = 6.0,
                                                        ["x"] = 3.0,
                                                        ["w"] = 1912.0,
                                                        ["h"] = 1030.0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["geom"] = {
                                                ["y"] = 20.0,
                                                ["x"] = 1.0,
                                                ["w"] = 1918.0,
                                                ["h"] = 1043.0,
                                            },
                                            ["name"] = "WGroupCW<3>",
                                            ["switchto"] = true,
                                            ["type"] = "WGroupCW",
                                        },
                                        [5] = {
                                            ["level"] = 0.0,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["level"] = 1.0,
                                                    ["sizepolicy"] = "full",
                                                    ["checkcode"] = 5.0,
                                                    ["bottom"] = true,
                                                    ["windowid"] = 41943053.0,
                                                    ["geom"] = {
                                                        ["y"] = 6.0,
                                                        ["x"] = 3.0,
                                                        ["w"] = 1912.0,
                                                        ["h"] = 1030.0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["name"] = "WGroupCW<4>",
                                            ["geom"] = {
                                                ["y"] = 20.0,
                                                ["x"] = 1.0,
                                                ["w"] = 1918.0,
                                                ["h"] = 1043.0,
                                            },
                                            ["type"] = "WGroupCW",
                                        },
                                    },
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["type"] = "WSplitSplit",
                        },
                        ["sizepolicy"] = "full",
                        ["bottom"] = true,
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1080.0,
                        },
                        ["name"] = "WTiling<3>",
                        ["level"] = 0.0,
                        ["type"] = "WTiling",
                    },
                },
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1080.0,
                },
                ["switchto"] = true,
                ["name"] = "WGroupWS<3>",
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["type"] = "WGroupWS",
            },
            [4] = {
                ["unnumbered"] = true,
                ["pseudomodal"] = true,
                ["geom"] = {
                    ["y"] = 0.0,
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1080.0,
                },
                ["initial_outputs"] = {
                },
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["level"] = 1025.0,
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["mode"] = 0.0,
                        ["bottom"] = true,
                        ["name"] = "*scratchpad*",
                        ["geom"] = {
                            ["y"] = 151.0,
                            ["x"] = 467.0,
                            ["w"] = 998.0,
                            ["h"] = 764.0,
                        },
                        ["type"] = "WFrame",
                    },
                },
                ["name"] = "*scratchws*",
                ["level"] = 1.0,
                ["type"] = "WGroupWS",
            },
        },
        ["type"] = "WScreen",
    },
}

