-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                },
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["h"] = 1080.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                        },
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                    ["managed"] = {
                                    },
                                    ["name"] = "Tiling Frame",
                                },
                            },
                            ["dir"] = "horizontal",
                            ["tl"] = {
                                ["type"] = "WSplitSplit",
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["dir"] = "vertical",
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["saved_w"] = 1920.0,
                                        ["saved_x"] = 0.0,
                                        ["name"] = "WFrame<1>",
                                        ["saved_h"] = 1065.0,
                                        ["mode"] = 1.0,
                                        ["saved_y"] = 0.0,
                                        ["managed"] = {
                                        },
                                    },
                                },
                                ["tls"] = 1065.0,
                                ["brs"] = 15.0,
                            },
                            ["tls"] = 960.0,
                            ["brs"] = 960.0,
                        },
                        ["level"] = 0.0,
                    },
                },
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["name"] = "WGroupWS<2>",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                },
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<2>",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["h"] = 1080.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                        },
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["type"] = "WFrame",
                                ["mode"] = 1.0,
                                ["managed"] = {
                                },
                                ["name"] = "WFrame<3>",
                            },
                        },
                        ["level"] = 0.0,
                    },
                },
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["name"] = "WGroupWS<3>",
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["level"] = 0.0,
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<3>",
                        ["geom"] = {
                            ["y"] = 0.0,
                            ["h"] = 1080.0,
                            ["w"] = 1920.0,
                            ["x"] = 0.0,
                        },
                        ["bottom"] = true,
                        ["split_tree"] = {
                            ["type"] = "WSplitSplit",
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1.0,
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<5>",
                                },
                            },
                            ["tls"] = 1064.0,
                            ["brs"] = 16.0,
                        },
                        ["level"] = 0.0,
                    },
                },
            },
            [4] = {
                ["managed"] = {
                    [1] = {
                        ["type"] = "WFrame",
                        ["bottom"] = true,
                        ["sizepolicy"] = "free_glue",
                        ["name"] = "*scratchpad*",
                        ["geom"] = {
                            ["y"] = 151.0,
                            ["h"] = 764.0,
                            ["w"] = 998.0,
                            ["x"] = 467.0,
                        },
                        ["mode"] = 0.0,
                        ["level"] = 1025.0,
                        ["managed"] = {
                        },
                    },
                },
                ["unnumbered"] = true,
                ["pseudomodal"] = true,
                ["geom"] = {
                    ["y"] = 0.0,
                    ["h"] = 1080.0,
                    ["w"] = 1920.0,
                    ["x"] = 0.0,
                },
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["name"] = "*scratchws*",
                ["type"] = "WGroupWS",
                ["level"] = 1.0,
                ["initial_outputs"] = {
                },
            },
        },
        ["name"] = "WScreen",
    },
}

