-- This file has been generated by notion. Do not edit.
return {
    [1] = "run:firefox",
    [2] = "run:emacs",
    [3] = "run:chromium",
    [4] = "run:frefox",
    [5] = "run:gnome-screenshot -a",
    [6] = "run:firefo",
    [7] = "run:chromium=",
    [8] = "menu.mainmenu:session/restart",
    [9] = "workspacelayout:",
    [10] = "workspacename:newd",
}

