-- This file has been generated by notion. Do not edit.
return {
    [1] = "run:emacs",
    [2] = "run:chromium",
    [3] = "run:firefox",
    [4] = "run:chromium=",
    [5] = "menu.mainmenu:session/restart",
    [6] = "workspacelayout:",
    [7] = "workspacename:newd",
}

