-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [1] = "run:gnome-screenshot -a",
    [2] = "run:spotify",
    [3] = "run:vlc",
    [4] = "run:emacs",
    [5] = "run:emcas",
    [6] = "run:firefox",
    [7] = "windowname:emacs@novaria",
    [8] = "run:gnome-screenshot",
    [9] = "menu.mainmenu:session/exit",
    [10] = "run:pavucontrol",
    [11] = "run:chromium",
    [12] = "run:frefox",
    [13] = "run:firefo",
    [14] = "run:chromium=",
    [15] = "menu.mainmenu:session/restart",
    [16] = "workspacelayout:",
    [17] = "workspacename:newd",
}

