-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["name"] = "WTiling",
                        ["level"] = 0.0,
                        ["split_tree"] = {
                            ["tls"] = 960.0,
                            ["br"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "Tiling Frame<1>",
                                    ["mode"] = 1.0,
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "horizontal",
                            ["type"] = "WSplitSplit",
                            ["brs"] = 960.0,
                            ["tl"] = {
                                ["tls"] = 534.0,
                                ["br"] = {
                                    ["tls"] = 538.0,
                                    ["br"] = {
                                        ["type"] = "WSplitST",
                                    },
                                    ["dir"] = "vertical",
                                    ["type"] = "WSplitSplit",
                                    ["brs"] = 8.0,
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                            },
                                            ["type"] = "WFrame",
                                            ["name"] = "Tiling Frame<2>",
                                            ["mode"] = 1.0,
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                },
                                ["dir"] = "vertical",
                                ["type"] = "WSplitSplit",
                                ["brs"] = 546.0,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["type"] = "WFrame",
                                        ["name"] = "Tiling Frame",
                                        ["mode"] = 1.0,
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                            },
                        },
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1080.0,
                            ["y"] = 0.0,
                        },
                    },
                },
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1080.0,
                    ["y"] = 0.0,
                },
            },
            [2] = {
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["name"] = "WTiling<2>",
                        ["level"] = 0.0,
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<3>",
                                ["mode"] = 1.0,
                            },
                            ["type"] = "WSplitRegion",
                        },
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1080.0,
                            ["y"] = 0.0,
                        },
                    },
                },
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<2>",
                ["geom"] = {
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1080.0,
                    ["y"] = 0.0,
                },
            },
            [3] = {
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["name"] = "WTiling<3>",
                        ["level"] = 0.0,
                        ["split_tree"] = {
                            ["tls"] = 1064.0,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16.0,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["bottom"] = true,
                                                    ["level"] = 1.0,
                                                    ["windowid"] = 31457410.0,
                                                    ["checkcode"] = 1.0,
                                                    ["type"] = "WClientWin",
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["x"] = 0.0,
                                                        ["w"] = 1918.0,
                                                        ["h"] = 1044.0,
                                                        ["y"] = 0.0,
                                                    },
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["sizepolicy"] = "full",
                                            ["level"] = 0.0,
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["geom"] = {
                                                ["x"] = 1.0,
                                                ["w"] = 1918.0,
                                                ["h"] = 1044.0,
                                                ["y"] = 19.0,
                                            },
                                        },
                                        [2] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["bottom"] = true,
                                                    ["level"] = 1.0,
                                                    ["windowid"] = 29360147.0,
                                                    ["checkcode"] = 2.0,
                                                    ["type"] = "WClientWin",
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["x"] = 0.0,
                                                        ["w"] = 1918.0,
                                                        ["h"] = 1044.0,
                                                        ["y"] = 0.0,
                                                    },
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["sizepolicy"] = "full",
                                            ["level"] = 0.0,
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<1>",
                                            ["geom"] = {
                                                ["x"] = 1.0,
                                                ["w"] = 1918.0,
                                                ["h"] = 1044.0,
                                                ["y"] = 19.0,
                                            },
                                        },
                                        [3] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["bottom"] = true,
                                                    ["level"] = 1.0,
                                                    ["windowid"] = 56623117.0,
                                                    ["checkcode"] = 3.0,
                                                    ["type"] = "WClientWin",
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["x"] = 3.0,
                                                        ["w"] = 1912.0,
                                                        ["h"] = 1030.0,
                                                        ["y"] = 7.0,
                                                    },
                                                },
                                            },
                                            ["geom"] = {
                                                ["x"] = 1.0,
                                                ["w"] = 1918.0,
                                                ["h"] = 1044.0,
                                                ["y"] = 19.0,
                                            },
                                            ["sizepolicy"] = "full",
                                            ["level"] = 0.0,
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<5>",
                                            ["switchto"] = true,
                                        },
                                    },
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<5>",
                                    ["mode"] = 1.0,
                                },
                                ["type"] = "WSplitRegion",
                            },
                        },
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["x"] = 0.0,
                            ["w"] = 1920.0,
                            ["h"] = 1080.0,
                            ["y"] = 0.0,
                        },
                    },
                },
                ["geom"] = {
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1080.0,
                    ["y"] = 0.0,
                },
                ["sizepolicy"] = "full",
                ["level"] = 0.0,
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<3>",
                ["switchto"] = true,
            },
            [4] = {
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["managed"] = {
                            [1] = {
                                ["managed"] = {
                                    [1] = {
                                        ["bottom"] = true,
                                        ["level"] = 1.0,
                                        ["windowid"] = 44040193.0,
                                        ["checkcode"] = 4.0,
                                        ["type"] = "WClientWin",
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["x"] = 0.0,
                                            ["w"] = 1795.0,
                                            ["h"] = 1012.0,
                                            ["y"] = 0.0,
                                        },
                                    },
                                },
                                ["hidden"] = true,
                                ["sizepolicy"] = "full",
                                ["level"] = 0.0,
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<3>",
                                ["geom"] = {
                                    ["x"] = 2.0,
                                    ["w"] = 1795.0,
                                    ["h"] = 1012.0,
                                    ["y"] = 20.0,
                                },
                            },
                            [2] = {
                                ["managed"] = {
                                    [1] = {
                                        ["bottom"] = true,
                                        ["level"] = 1.0,
                                        ["windowid"] = 39845901.0,
                                        ["checkcode"] = 5.0,
                                        ["type"] = "WClientWin",
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["x"] = 0.0,
                                            ["w"] = 1795.0,
                                            ["h"] = 1012.0,
                                            ["y"] = 0.0,
                                        },
                                    },
                                },
                                ["hidden"] = true,
                                ["sizepolicy"] = "full",
                                ["level"] = 0.0,
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<2>",
                                ["geom"] = {
                                    ["x"] = 2.0,
                                    ["w"] = 1795.0,
                                    ["h"] = 1012.0,
                                    ["y"] = 20.0,
                                },
                            },
                            [3] = {
                                ["managed"] = {
                                    [1] = {
                                        ["bottom"] = true,
                                        ["level"] = 1.0,
                                        ["windowid"] = 50331649.0,
                                        ["checkcode"] = 6.0,
                                        ["type"] = "WClientWin",
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["x"] = 0.0,
                                            ["w"] = 1795.0,
                                            ["h"] = 1012.0,
                                            ["y"] = 0.0,
                                        },
                                    },
                                },
                                ["geom"] = {
                                    ["x"] = 2.0,
                                    ["w"] = 1795.0,
                                    ["h"] = 1012.0,
                                    ["y"] = 20.0,
                                },
                                ["sizepolicy"] = "full",
                                ["level"] = 0.0,
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<4>",
                                ["switchto"] = true,
                            },
                        },
                        ["sizepolicy"] = "free_glue",
                        ["mode"] = 0.0,
                        ["level"] = 1025.0,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["geom"] = {
                            ["x"] = 70.0,
                            ["w"] = 1799.0,
                            ["h"] = 1034.0,
                            ["y"] = 19.0,
                        },
                    },
                },
                ["hidden"] = true,
                ["level"] = 1.0,
                ["type"] = "WGroupWS",
                ["geom"] = {
                    ["x"] = 0.0,
                    ["w"] = 1920.0,
                    ["h"] = 1080.0,
                    ["y"] = 0.0,
                },
                ["unnumbered"] = true,
                ["pseudomodal"] = true,
                ["name"] = "*scratchws*",
                ["sizepolicy"] = "full",
            },
        },
    },
}

